version: '3.8'

services:
  app:
    build: .
    container_name: freetimefinder_app
    ports:
      - "${PORT}:8000"
    environment:
      - DEBUG=0
      - DJANGO_SECRET_KEY=your-secret-key-change-in-production
      - ALLOWED_HOSTS=*
      - CORS_ALLOWED_ORIGINS= # Not needed when served from the same domain
    volumes:
      - sqlite_data:/app/backend/db

volumes:
  sqlite_data: